const firebaseConfig={apiKey:"AIzaSyAS3UXXrio_-c9uPbHwpDuTV-rp8d903w",authDomain:"white-2k-17-v4.firebaseapp.com",databaseURL:"https://white-2k-17-v4-default-rtdb.firebaseio.com",projectId:"white-2k-17-v4",storageBucket:"white-2k-17-v4.firebasestorage.app",messagingSenderId:"180909174928",appId:"1:180909174928:android:148861a87d66c6980ca815"};
firebase.initializeApp(firebaseConfig);const db=firebase.database(),ref=db.ref("apps");let products=[];
const grid=document.getElementById("productGrid"),modal=document.getElementById("detailModal"),viewer=document.getElementById("imageViewer"),viewerImage=document.getElementById("viewerImage"),videoViewer=document.getElementById("videoViewer"),viewerVideo=document.getElementById("viewerVideo");
ref.on("value",snap=>{const data=snap.val()||{};products=Object.entries(data).map(([id,p])=>normalize({...p,id}));render()},()=>grid.innerHTML='<div class="empty">Could not load products.</div>');
function normalize(p){let previews=Array.isArray(p.previews)?p.previews.filter(Boolean):Object.values(p.previews||{}).filter(Boolean);return {...p,title:p.title||"Untitled",price:p.price??"Free",oldPrice:p.oldPrice??"",description:p.description||"",image:p.image||"",previews:previews.slice(0,5),youtube:p.youtube||"",buyUrl:p.buyUrl||""}}
function num(v){const n=parseFloat(String(v).replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null}
function discount(p){const old=num(p.oldPrice),cur=num(p.price);if(old!==null&&cur!==null&&old>cur)return Math.round((old-cur)/old*100);return null}
function money(v){if(v===undefined||v===null||v===""||String(v).toLowerCase()==="free")return"FREE";return"৳ "+String(v)}
function priceHtml(p,detail=false){const d=discount(p),cur=`<span class="${detail?'currentPrice':'cardPrice'}">${esc(money(p.price))}</span>`;if(!d)return cur;return `${cur}<span class="${detail?'detailOld':'oldPrice'}">${esc(money(p.oldPrice))}</span>${detail?`<span class="detailDiscount">${d}% OFF</span>`:''}`}
function render(){if(!products.length){grid.innerHTML='<div class="empty">No products available.</div>';return}grid.innerHTML=products.map(p=>{const d=discount(p);return `<article class="card" data-id="${esc(p.id)}">${d?`<span class="cardDiscount">${d}% OFF</span>`:''}<img class="cardImg" src="${esc(p.image||placeholder())}" alt="${esc(p.title)}" loading="lazy"><div class="cardInfo"><div class="cardName">${esc(p.title)}</div><div class="cardPriceRow">${priceHtml(p)}</div></div></article>`}).join("");document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProduct(c.dataset.id))}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;
 document.getElementById('detailPrice').innerHTML=priceHtml(p,true);document.getElementById('detailTitle').textContent=p.title;document.getElementById('detailDescription').textContent=p.description||'';document.getElementById('detailDescriptionWrap').classList.toggle('show',!!p.description.trim());
 // The main product image is a fixed, non-scrolling hero. Review screenshots/video stay in the horizontal strip below.
 const hero=document.getElementById('detailHero');hero.innerHTML=p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)}" data-large-image="${esc(p.image)}">`:`<img src="${placeholder()}" alt="${esc(p.title)}">`;
 const y=extractYoutube(p.youtube);const previewItems=(p.previews||[]).slice(0,5);
 const rs=document.getElementById('reviewSection'),rt=document.getElementById('reviewThumbs');let html='';if(y)html+=`<button class="reviewThumb videoThumb" data-video-id="${esc(y)}"><span class="playIcon">▶</span><span class="videoLabel">Review Video</span></button>`;html+=previewItems.map((x,i)=>`<button class="reviewThumb" data-review-image="${esc(x)}"><img src="${esc(x)}" alt="Review screenshot ${i+1}"></button>`).join('');rt.innerHTML=html;rs.classList.toggle('show',!!html);
 document.querySelectorAll('[data-review-image]').forEach(b=>b.onclick=()=>openImage(b.dataset.reviewImage));document.querySelectorAll('[data-video-id]').forEach(b=>b.onclick=()=>openVideo(b.dataset.videoId));document.querySelectorAll('[data-large-image]').forEach(img=>img.onclick=()=>openImage(img.dataset.largeImage));
 const btn=document.getElementById('buyButton');btn.href=p.buyUrl||'#';btn.classList.toggle('disabled',!p.buyUrl);
 setTimeout(()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'},180)}
document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeDetail();if(e.target.closest('[data-viewer-close]')||e.target===viewer)closeImage();if(e.target.closest('[data-video-close]')||e.target===videoViewer)closeVideo()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeImage();closeVideo();closeDetail()}});
function closeDetail(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');if(!viewer.classList.contains('open')&&!videoViewer.classList.contains('open'))document.body.style.overflow='';}
function openImage(src){viewerImage.src=src;viewer.classList.add('open');viewer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';viewerImage.style.transform='scale(1)';viewerImage.dataset.scale='1';let startDist=0,startScale=1;const dist=(a,b)=>Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);viewerImage.ontouchstart=e=>{if(e.touches.length===2)startDist=dist(e.touches[0],e.touches[1]);else if(e.touches.length===1)startScale=parseFloat(viewerImage.dataset.scale||'1')};viewerImage.ontouchmove=e=>{if(e.touches.length===2&&startDist){const s=Math.min(4,Math.max(1,startScale*dist(e.touches[0],e.touches[1])/startDist));viewerImage.style.transform=`scale(${s})`;viewerImage.dataset.scale=s;e.preventDefault()}};viewerImage.ondblclick=()=>{const s=parseFloat(viewerImage.dataset.scale||'1')>1?1:2;viewerImage.dataset.scale=s;viewerImage.style.transform=`scale(${s})`}}
function closeImage(){viewer.classList.remove('open');viewer.setAttribute('aria-hidden','true');viewerImage.src='';viewerImage.dataset.scale='1';viewerImage.style.transform='scale(1)';if(!modal.classList.contains('open')&&!videoViewer.classList.contains('open'))document.body.style.overflow=''}
function openVideo(id){viewerVideo.src=`https://www.youtube.com/embed/${encodeURIComponent(id)}?autoplay=1&playsinline=1&rel=0`;videoViewer.classList.add('open');videoViewer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeVideo(){videoViewer.classList.remove('open');videoViewer.setAttribute('aria-hidden','true');viewerVideo.src='';if(!modal.classList.contains('open')&&!viewer.classList.contains('open'))document.body.style.overflow=''}
function extractYoutube(url){if(!url)return'';try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.hostname.includes('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v')||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||''}}catch(e){}return''}
function placeholder(){return'https://placehold.co/900x900/15171c/f4f4f4?text=MTA+Gadget+Shop'}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
